name: build-test-on-master-push
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Install dependencies
        run: bundle install
      - name: Migrate DB if needed
        run: rails db:migrate RAILS_ENV=test
      - name: Run unit tests
        run: bundle exec rake
      - name: Install ChromeDriver
        run: sudo apt-get install chromium-chromedriver
      - name: Run System tests
        run: rails test:system
