name: build-test-on-master-push
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: Install dependencies
        run: bundle install
      - name: Migrate DB if needed
        run: rails db:migrate RAILS_ENV=test
      - name: Run unit tests
        run: bundle exec rake
      - name: Install Chrome
        run: |
          curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip" 
          cd /tmp 
          unzip chromedriver_linux64.zip 
          rm -rf chromedriver_linux64.zip 
          sudo mv chromedriver /usr/local/bin/chromedriver 
          sudo chmod +x /usr/local/bin/chromedriver 
          chromedriver --version
      - name: Run System tests
        run: rails test:system
